CREATE TABLE IF NOT EXISTS users (
    id         INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    username   TEXT NOT NULL UNIQUE,
    password   TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_permissions (
    user_id    INTEGER NOT NULL,
    token      TEXT NOT NULL
);
