[workspace]
default-members = ["web"]
members = [
  "core",
  "desktop",
  "web"
]
resolver = "2"

[patch.'https://github.com/open-spaced-repetition/rs-fsrs']
fsrs = { path = "../rs-fsrs", features = ["serde"] }
