[package]
name = "brainace_core"
description = "The essential ideas of Brainace"
version = "0.0.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
fsrs = { git = "https://github.com/open-spaced-repetition/fsrs-rs.git" }
# chrono = "0.4.31"
serde = "1.0.195"
